HTTP;- HTTP Methods batate hain ki tum server se kya karna chahte ho:

GET — data mangwana (read-only, kuch change nahi hota)
POST — data bhejna (server par naya kuch create/save karna)
PUT/PATCH — update karna, DELETE — hatana

1.GET request — data fetch karna (jo humne Day 25B mein already kiya):

In [1]:
import requests

response = requests.get('https://jsonplaceholder.typicode.com/posts/1')
print(response.status_code)
print(response.json())

200
{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}


jsonplaceholder.typicode.com ek free "fake" API hai jo testing ke liye bani hai — real data save nahi hota, lekin practice ke liye perfect hai.

2.GET request with query parameters — filtering jaisa (SQL WHERE jaisa concept):

In [2]:
response = requests.get(
    'https://jsonplaceholder.typicode.com/posts',
    params={'userId': 1}
)
data = response.json()
print(f"Total posts by userId=1: {len(data)}")
print(data[0])

Total posts by userId=1: 10
{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}


3.POST request — naya data server par bhejna:

In [3]:
new_post = {
    'title': 'Churn Prediction Project Update',
    'body': 'Completed Month 1 SQL foundations and started Month 2 Python basics.',
    'userId': 1
}

response = requests.post(
    'https://jsonplaceholder.typicode.com/posts',
    json=new_post   # json= use karo, yeh automatically JSON format mein convert kar deta hai
)
print(response.status_code)   # 201 = Created (successfully bana)
print(response.json())        # server jo response bheja, usme naya 'id' bhi milega

201
{'title': 'Churn Prediction Project Update', 'body': 'Completed Month 1 SQL foundations and started Month 2 Python basics.', 'userId': 1, 'id': 101}


json=new_post parameter automatically Python dictionary ko JSON string mein convert karke bhejta hai, aur request header mein Content-Type: application/json bhi set kar deta hai — manually karne ki zaroorat nahi.

4.Status codes samajhna (important — debugging ke liye kaam aayega):

In [4]:
# GET — success
r1 = requests.get('https://jsonplaceholder.typicode.com/posts/1')
print(f"GET success: {r1.status_code}")   # 200

# POST — successfully created
r2 = requests.post('https://jsonplaceholder.typicode.com/posts', json={'title': 'test'})
print(f"POST success: {r2.status_code}")   # 201

# Galat URL — not found
r3 = requests.get('https://jsonplaceholder.typicode.com/posts/99999999')
print(f"Not found: {r3.status_code}")   # 404 ya empty response

GET success: 200
POST success: 201
Not found: 404


Yaad rakhne wale common codes: 200 OK, 201 Created, 400 Bad Request (galat data bheja), 401 Unauthorized (login/API key chahiye), 404 Not Found, 500 Server Error.

5.GET vs POST practical difference — jab tum FastAPI banaoge (Phase 7, Day 122), tumhara /predict endpoint POST hoga, kyunki customer data bhejna padega prediction lene ke liye:

In [5]:
# Yeh exactly waisa hi hoga jaisa aage FastAPI mein banaoge:
customer_data = {
    'recency_days': 45,
    'frequency': 12,
    'monetary': 2500
}

# Abhi koi real churn-predict API nahi hai, isliye jsonplaceholder par hi simulate karte hain
response = requests.post('https://jsonplaceholder.typicode.com/posts', json=customer_data)
print("Simulated churn-predict request:", response.json())

Simulated churn-predict request: {'recency_days': 45, 'frequency': 12, 'monetary': 2500, 'id': 101}


Practice questions

1.jsonplaceholder.typicode.com/users par GET request bhejo aur sirf pehle user ka name aur email print karo.

In [8]:
# GET request bhej kar users ka data fetch karna
response = requests.get('https://jsonplaceholder.typicode.com/users')
users = response.json()

# Agar data successfully mil gaya, toh pehle user ka name aur email print karenge
if response.status_code == 200 and len(users) > 0:
    first_user = users[0]
    print(f"Name: {first_user['name']}")
    print(f"Email: {first_user['email']}")
else:
    print("Data fetch karne mein kuch gadbad hui:", response.status_code)

Name: Leanne Graham
Email: Sincere@april.biz


2.Ek POST request banao jisme tumhara khud ka naam aur project ka title ho, aur response mein dekho server ne kya id assign kiya.

In [9]:
# Apna data define karna
my_data = {
    'name': 'Aapka Naam',  # Yahan apna naam likh sakte hain
    'project_title': 'Churn Prediction Project',
    'body': 'Learning HTTP methods and REST APIs.'
}

# POST request ke zariye data server par bhejna
response = requests.post(
    'https://jsonplaceholder.typicode.com/posts',
    json=my_data
)

# Status code aur server dwara assign kiya gaya 'id' check karna
print(f"Status Code: {response.status_code}")  # 201 Created aana chahiye
response_json = response.json()
print("Server Response:", response_json)
print(f"Server ne assigned ID: {response_json.get('id')}")

Status Code: 201
Server Response: {'name': 'Aapka Naam', 'project_title': 'Churn Prediction Project', 'body': 'Learning HTTP methods and REST APIs.', 'id': 101}
Server ne assigned ID: 101
